sudo: required
services:
  - docker

before_install:
   - docker build -t alexpietrareanu/react-test -f ./client/Dockerfile.dev ./client

script:
   -  docker run -e CI=true alexpietrareanu/react-test npm test

after_success:
  - docker build -t alexpietrareanu/multi-client ./client
  - docker build -t alexpietrareanu/multi-nginx ./nginx
  - docker build -t alexpietrareanu/multi-server ./server
  - docker build -t alexpietrareanu/multi-worker ./worker
  #Log in to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #Take those images and push them to docker
  - docker push alexpietrareanu/multi-client
  - docker push alexpietrareanu/multi-nginx
  - docker push alexpietrareanu/multi-server
  - docker push alexpietrareanu/multi-worker